### ISSUE TITLE
New CN localizations

### ISSUE THREAD

**Issue by wuhan890809** [onechiporenko/my-dungeons-book#110]
Hello onechiporenko
it's me again ,i'm here to provide newly-added localized strings.
I was not playing for last half month,so I missed two recent updates.

(After line 114: L["Avoidable"] = "可规避"; Before line 134: -- UI end)

L["Talents"] = "天赋";
L["Covenant"] = "盟约";
L["Equipment"] = "装备";
L["Info"] = "信息";
L["Covenant info is available only about players with installed MyDungeonsBook."] = "只能显示安装了MyDungeonsBook的玩家的盟约信息。";
L["WowHead"] = "WowHead";
L["WowHead Link for %s"] = "%s的WowHead链接";
L["Report"] = "报告";
L["To Self"] = "向自己";
L["To Target"] = "向目标";
L["To Group/Raid"] = "向小队/团队";
L["MyDungeonsBook %s Usage:"] = "MyDungeonsBook %s 使用:";
L["MyDungeonsBook %s Interrupted:"] = "MyDungeonsBook %s 打断:";
L["MyDungeonsBook %s Casts:"] = "MyDungeonsBook %s 施法:";
L["MyDungeonsBook Damage taken by party from %s:"] = "MyDungeonsBook 小队承受来自 %s 的伤害:";
L["MyDungeonsBook Heal done by %s with %s:"] = "MyDungeonsBook 来自 %s 的治疗，通过 %s:";
L["MyDungeonsBook Damage done by party to %s:"] = "MyDungeonsBook 小队向 %s 输出的伤害:";
L["MyDungeonsBook %s Dispelled:"] = "MyDungeonsBook %s 驱散:";
L["MyDungeonsBook Debuff %s hits:"] = "MyDungeonsBook Debuff %s 命中:";

(After line 140: L["print this text."] = "显示这段文字。"; Before line 142: -- Help end)

L["send some message via comm to other MDB user. unitId must be 'party1..4'."] = "通过聊天向其他MDB用户发送信息。单位ID(unitId)必须是'party1..4'这种形式";

And I found one small mistake i made during last translation.
(in line 153: L["Date Format"] = "数据格式";)
I mistake "Date" for "Data" XD, so the correct one should be:
L["Date Format"] = "日期格式";

By the way ,I noticed the new UI panel design, it's clean.

**Comment by onechiporenko** [comment]
Thanks @wuhan890809!
