### ISSUE TITLE
Can't see any details

### ISSUE THREAD

**Issue by Sagezez** [onechiporenko/my-dungeons-book#117]
Hi, the DB has been working really well and I use it all the time until a couple of days ago. It still collects data from the runs but can not view them in the right pane when I chose a run on the left. It stays blank.

![image](https://user-images.githubusercontent.com/83190677/116013289-c403d480-a672-11eb-8868-6616ddebf23b.png)
![image](https://user-images.githubusercontent.com/83190677/116013311-e0a00c80-a672-11eb-98b1-2c36dc040a42.png)

**Comment by onechiporenko** [comment]
@Sagezez thanks for the report. Going to fix this.

**Comment by onechiporenko** [comment]
@Sagezez as a workaround you can edit file `Interface\AddOns\MyDungeonsBook\Locales\ruRU.lua` and add a line
```
if not L then return end
```
right after
```
local L = LibStub("AceLocale-3.0"):NewLocale("MyDungeonsBook", "ruRU");
```

**Comment by onechiporenko** [comment]
`v2.9.0` is published. Issue should be fixed

**Comment by Sagezez** [comment]
Yes! Thank you so much it is fixed. This is a great addon and I really appreciate all the work you have put in to make it so good.

Thank you!

**Comment by onechiporenko** [comment]
@Sagezez thanks! I'm realy glad to see happy users :)
