### ISSUE TITLE
10.1 lua error

### ISSUE THREAD

**Issue by srbrunner** [onechiporenko/my-dungeons-book#119]
I am getting this lua error since 10.1

MyDungeonsBook/Events.lua:553: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@MyDungeonsBook/Events.lua"]:553: in function `?'
[string "@(D)BrokerVolume/Libs/CallbackHandler-1.0-8.lua"]:145: in function <(D)BrokerVolume/Libs/CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[7]"]:4: in function <[string "safecall Dispatcher[7]"]:4>
[string "=[C]"]: ?
[string "safecall Dispatcher[7]"]:13: in function `?'
[string "@(D)BrokerVolume/Libs/CallbackHandler-1.0-8.lua"]:90: in function `Fire'
[string "@AskMrRobot/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <AskMrRobot/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "Challenge %s does not exist"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by onechiporenko** [comment]
Hi, @srbrunner. Thanks for report. `v2.31.0` will have a fix.
